// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/client.proto

package clientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED       Status = 0
	Status_STATUS_SUCCESS           Status = 1
	Status_STATUS_NOT_LEADER        Status = 2
	Status_STATUS_NO_LEADER         Status = 3
	Status_STATUS_TIMEOUT           Status = 4
	Status_STATUS_INVALID_REQUEST   Status = 5
	Status_STATUS_REQUEST_ID_REUSED Status = 6
	Status_STATUS_OVERLOADED        Status = 7
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_NOT_LEADER",
		3: "STATUS_NO_LEADER",
		4: "STATUS_TIMEOUT",
		5: "STATUS_INVALID_REQUEST",
		6: "STATUS_REQUEST_ID_REUSED",
		7: "STATUS_OVERLOADED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":       0,
		"STATUS_SUCCESS":           1,
		"STATUS_NOT_LEADER":        2,
		"STATUS_NO_LEADER":         3,
		"STATUS_TIMEOUT":           4,
		"STATUS_INVALID_REQUEST":   5,
		"STATUS_REQUEST_ID_REUSED": 6,
		"STATUS_OVERLOADED":        7,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_client_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_client_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=raftkv.client.v1.Status" json:"status,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,5,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	RetryAfterMs  int64                  `protobuf:"varint,6,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

func (x *GetResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proto_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=raftkv.client.v1.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	RetryAfterMs  int64                  `protobuf:"varint,4,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_proto_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{3}
}

func (x *SetResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *SetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SetResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

func (x *SetResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=raftkv.client.v1.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	RetryAfterMs  int64                  `protobuf:"varint,4,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *DeleteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeleteResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

func (x *DeleteResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	LastContact   int64                  `protobuf:"varint,3,opt,name=last_contact,json=lastContact,proto3" json:"last_contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{6}
}

func (x *NodeStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NodeStatus) GetLastContact() int64 {
	if x != nil {
		return x.LastContact
	}
	return 0
}

type ClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusRequest) Reset() {
	*x = ClusterStatusRequest{}
	mi := &file_proto_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusRequest) ProtoMessage() {}

func (x *ClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*ClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{7}
}

type ClusterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=raftkv.client.v1.Status" json:"status,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Term          uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Nodes         []*NodeStatus          `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,6,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	RetryAfterMs  int64                  `protobuf:"varint,7,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_proto_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{8}
}

func (x *ClusterStatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ClusterStatusResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *ClusterStatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ClusterStatusResponse) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ClusterStatusResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

func (x *ClusterStatusResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_proto_client_proto protoreflect.FileDescriptor

const file_proto_client_proto_rawDesc = "" +
	"\n" +
	"\x12proto/client.proto\x12\x10raftkv.client.v1\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xd7\x01\n" +
	"\vGetResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.raftkv.client.v1.StatusR\x06status\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vleader_hint\x18\x05 \x01(\tR\n" +
	"leaderHint\x12$\n" +
	"\x0eretry_after_ms\x18\x06 \x01(\x03R\fretryAfterMs\"S\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\xab\x01\n" +
	"\vSetResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.raftkv.client.v1.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\x12$\n" +
	"\x0eretry_after_ms\x18\x04 \x01(\x03R\fretryAfterMs\"@\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\xae\x01\n" +
	"\x0eDeleteResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.raftkv.client.v1.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\x12$\n" +
	"\x0eretry_after_ms\x18\x04 \x01(\x03R\fretryAfterMs\"S\n" +
	"\n" +
	"NodeStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12!\n" +
	"\flast_contact\x18\x03 \x01(\x03R\vlastContact\"\x16\n" +
	"\x14ClusterStatusRequest\"\x9a\x02\n" +
	"\x15ClusterStatusResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.raftkv.client.v1.StatusR\x06status\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x122\n" +
	"\x05nodes\x18\x04 \x03(\v2\x1c.raftkv.client.v1.NodeStatusR\x05nodes\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vleader_hint\x18\x06 \x01(\tR\n" +
	"leaderHint\x12$\n" +
	"\x0eretry_after_ms\x18\a \x01(\x03R\fretryAfterMs*\xc6\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x15\n" +
	"\x11STATUS_NOT_LEADER\x10\x02\x12\x14\n" +
	"\x10STATUS_NO_LEADER\x10\x03\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x04\x12\x1a\n" +
	"\x16STATUS_INVALID_REQUEST\x10\x05\x12\x1c\n" +
	"\x18STATUS_REQUEST_ID_REUSED\x10\x06\x12\x15\n" +
	"\x11STATUS_OVERLOADED\x10\a2\xc6\x02\n" +
	"\rClientService\x12B\n" +
	"\x03Get\x12\x1c.raftkv.client.v1.GetRequest\x1a\x1d.raftkv.client.v1.GetResponse\x12B\n" +
	"\x03Set\x12\x1c.raftkv.client.v1.SetRequest\x1a\x1d.raftkv.client.v1.SetResponse\x12K\n" +
	"\x06Delete\x12\x1f.raftkv.client.v1.DeleteRequest\x1a .raftkv.client.v1.DeleteResponse\x12`\n" +
	"\rClusterStatus\x12&.raftkv.client.v1.ClusterStatusRequest\x1a'.raftkv.client.v1.ClusterStatusResponseB!Z\x1fraftkv/proto/client/v1;clientv1b\x06proto3"

var (
	file_proto_client_proto_rawDescOnce sync.Once
	file_proto_client_proto_rawDescData []byte
)

func file_proto_client_proto_rawDescGZIP() []byte {
	file_proto_client_proto_rawDescOnce.Do(func() {
		file_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_proto_rawDesc), len(file_proto_client_proto_rawDesc)))
	})
	return file_proto_client_proto_rawDescData
}

var file_proto_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_client_proto_goTypes = []any{
	(Status)(0),                   // 0: raftkv.client.v1.Status
	(*GetRequest)(nil),            // 1: raftkv.client.v1.GetRequest
	(*GetResponse)(nil),           // 2: raftkv.client.v1.GetResponse
	(*SetRequest)(nil),            // 3: raftkv.client.v1.SetRequest
	(*SetResponse)(nil),           // 4: raftkv.client.v1.SetResponse
	(*DeleteRequest)(nil),         // 5: raftkv.client.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 6: raftkv.client.v1.DeleteResponse
	(*NodeStatus)(nil),            // 7: raftkv.client.v1.NodeStatus
	(*ClusterStatusRequest)(nil),  // 8: raftkv.client.v1.ClusterStatusRequest
	(*ClusterStatusResponse)(nil), // 9: raftkv.client.v1.ClusterStatusResponse
}
var file_proto_client_proto_depIdxs = []int32{
	0, // 0: raftkv.client.v1.GetResponse.status:type_name -> raftkv.client.v1.Status
	0, // 1: raftkv.client.v1.SetResponse.status:type_name -> raftkv.client.v1.Status
	0, // 2: raftkv.client.v1.DeleteResponse.status:type_name -> raftkv.client.v1.Status
	0, // 3: raftkv.client.v1.ClusterStatusResponse.status:type_name -> raftkv.client.v1.Status
	7, // 4: raftkv.client.v1.ClusterStatusResponse.nodes:type_name -> raftkv.client.v1.NodeStatus
	1, // 5: raftkv.client.v1.ClientService.Get:input_type -> raftkv.client.v1.GetRequest
	3, // 6: raftkv.client.v1.ClientService.Set:input_type -> raftkv.client.v1.SetRequest
	5, // 7: raftkv.client.v1.ClientService.Delete:input_type -> raftkv.client.v1.DeleteRequest
	8, // 8: raftkv.client.v1.ClientService.ClusterStatus:input_type -> raftkv.client.v1.ClusterStatusRequest
	2, // 9: raftkv.client.v1.ClientService.Get:output_type -> raftkv.client.v1.GetResponse
	4, // 10: raftkv.client.v1.ClientService.Set:output_type -> raftkv.client.v1.SetResponse
	6, // 11: raftkv.client.v1.ClientService.Delete:output_type -> raftkv.client.v1.DeleteResponse
	9, // 12: raftkv.client.v1.ClientService.ClusterStatus:output_type -> raftkv.client.v1.ClusterStatusResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_client_proto_init() }
func file_proto_client_proto_init() {
	if File_proto_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_proto_rawDesc), len(file_proto_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_client_proto_goTypes,
		DependencyIndexes: file_proto_client_proto_depIdxs,
		EnumInfos:         file_proto_client_proto_enumTypes,
		MessageInfos:      file_proto_client_proto_msgTypes,
	}.Build()
	File_proto_client_proto = out.File
	file_proto_client_proto_goTypes = nil
	file_proto_client_proto_depIdxs = nil
}
